Make the test driver executable from nowhere
And don't mix tests output with the test driver output, it can easily
scramble the overall output.

diff --git a/src/tests/runtests b/src/tests/runtests
--- a/src/tests/runtests
+++ b/src/tests/runtests
@@ -1,15 +1,20 @@
 #!/bin/bash
 # (until we get automake/autoconf configured right.)
 
-set -o errexit
+set -e
 
-for t in test*; do
-	echo -n -e "$t\t"
-	bash $t
-	if [ "$?" != "0" ]; then
-		echo "FAILED"
+TESTDIR="$(dirname "$0")"
+
+cd "$TESTDIR"
+set -- ./test*
+
+for TEST
+do
+	if "$TEST"
+	then
+		printf "%s\tOK\n" "$TEST"
 	else
-		echo "OK"
+		printf "%s\tFAILED\n" "$TEST"
+		false
 	fi
 done
-
