Set sni-nomatch-abort per frontend.

diff --git a/src/tests/test07-nomatch-abort b/src/tests/test07-nomatch-abort
--- a/src/tests/test07-nomatch-abort
+++ b/src/tests/test07-nomatch-abort
@@ -7,9 +7,30 @@ set +o errexit
 
 #PORT2=$(($RANDOM + 1024))
 
-$HITCH $HITCH_ARGS --backend=[hitch-tls.org]:80 --frontend=[${LISTENADDR}]:$LISTENPORT \
-	certs/site1.example.com certs/site2.example.com certs/default.example.com \
-	--sni-nomatch-abort
+mk_cfg <<EOF
+sni-nomatch-abort = on
+
+pem-file = "$TESTDIR/certs/site1.example.com"
+pem-file = "$TESTDIR/certs/site2.example.com"
+pem-file = "$TESTDIR/certs/default.example.com"
+
+backend = "[hitch-tls.org]:80"
+
+frontend = {
+	host = "$LISTENADDR"
+	port = "$LISTENPORT"
+}
+
+frontend = {
+	host = "$LISTENADDR"
+	port = "$((LISTENPORT+1))"
+	pem-file = "$TESTDIR/certs/site3.example.com"
+	sni-nomatch-abort = off
+}
+
+EOF
+
+$HITCH $HITCH_ARGS --config=$CONFFILE
 test "$?" = "0" || die "Hitch did not start."
 
 # No SNI - should not be affected.
@@ -32,3 +53,15 @@ test "$?" = "0" || die "Expected 'unrecognized name' error."
 
 CURL_EXTRA="--resolve site1.example.com:$LISTENPORT:127.0.0.1"
 runcurl site1.example.com $LISTENPORT
+
+# SNI request w/ valid servername
+echo -e "\n" | openssl s_client -servername site1.example.com -prexit -connect $LISTENADDR:$((LISTENPORT+1)) 2>/dev/null > $DUMPFILE
+test "$?" = "0" || die "s_client failed"
+grep -q -c "subject=/CN=site3.example.com" $DUMPFILE
+test "$?" = "0" || die "s_client got wrong certificate in listen port #2"
+
+# SNI w/ unknown servername
+echo | openssl s_client -servername invalid.example.com -prexit -connect $LISTENADDR:$((LISTENPORT+1)) > $DUMPFILE 2>&1
+test "$?" = "0" || die "s_client failed"
+grep -q -c "subject=/CN=site3.example.com" $DUMPFILE
+test "$?" = "0" || die "s_client got wrong certificate in listen port #2"
